In [1]:
import numpy as np


# création d'une matrice

In [2]:
a = np.zeros((2,3))
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [3]:
b = np.ones((3,2))
b

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [4]:
v = np.array([1,2,3])
v

array([1, 2, 3])

# taille et transposition

In [5]:
b.shape

(3, 2)

In [6]:
b.T

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [7]:
v.shape

(3,)

In [8]:
v2d = np.atleast_2d(v)
v2d.shape

(1, 3)

# sauvegarde d'une matrice dans un fichier

In [9]:
r = np.random.rand(3,3)
r

array([[ 0.35329736,  0.32123513,  0.33647291],
       [ 0.19397138,  0.01047765,  0.1261015 ],
       [ 0.35628053,  0.79838703,  0.2634956 ]])

In [10]:
np.savetxt('random_mat.csv',r,delimiter=',',fmt='%.3e')

In [11]:
for l in open('random_mat.csv'):
    print(l)

3.533e-01,3.212e-01,3.365e-01

1.940e-01,1.048e-02,1.261e-01

3.563e-01,7.984e-01,2.635e-01



In [12]:
rr = np.loadtxt('random_mat.csv',delimiter=',')
rr

array([[ 0.3533 ,  0.3212 ,  0.3365 ],
       [ 0.194  ,  0.01048,  0.1261 ],
       [ 0.3563 ,  0.7984 ,  0.2635 ]])

# slicing/indexation

In [13]:
r

array([[ 0.35329736,  0.32123513,  0.33647291],
       [ 0.19397138,  0.01047765,  0.1261015 ],
       [ 0.35628053,  0.79838703,  0.2634956 ]])

In [14]:
r[0,2]

0.33647291459130169

In [15]:
r[:,0]

array([ 0.35329736,  0.19397138,  0.35628053])

In [16]:
r[0,:]

array([ 0.35329736,  0.32123513,  0.33647291])

In [17]:
m = [0,1,2]
n = [1,1,0]
r[m,n]

array([ 0.32123513,  0.01047765,  0.35628053])

# broatcasting

In [18]:
#!!! multiplication terme à terme
a*b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [ ]:
a*b.T

In [ ]:
b*2

In [ ]:
c = a + 1
c

In [ ]:
c*v

# produit scalaire

In [ ]:
np.dot(a,b)

In [ ]:
np.dot(c,v)

# Déterminant et inversion de matrice

In [ ]:
d = np.linalg.det(r)
d

In [ ]:
np.linalg.det(np.identity(3))

In [ ]:
np.linalg.det(np.array([[1,0,0],[0,2,0],[0,0,3]]))

In [ ]:
ir = np.linalg.inv(r)
ir

In [ ]:
p = np.dot(ir,r)
p

In [ ]:
np.round(p,decimals=2)

résolution d'un système linéaire

$
\begin{align}
x+y =2\\
2x+y = 3
\end{align}
$

notation matricielle:
$ ax = b $

avec

$a =
\left(
\begin{array}{cc}
1 & 1\\
2 & 1\\
\end{array}
\right)$

et

$b =
\left(
\begin{array}{c}
1 \\
2 \\
\end{array}
\right)$

$a^{-1}.a x = I.x =  a^{-1}.b$

$x = a^{-1}.b$


In [ ]:
a = np.array([[1,1],[2,1]])
b = np.array([2,3])
inv_a = np.linalg.inv(a)
np.dot(inv_a,b)

# vitesse

In [ ]:
r = np.random.rand(3,3)
%timeit ir = np.linalg.inv(r)

In [ ]:
r = np.random.rand(3000,3000)
%timeit np.linalg.inv(r)

In [ ]:
p = np.dot(np.linalg.inv(r),r)

In [ ]:
import matplotlib.pyplot as plt
%pylab inline
plt.figure(figsize=[10,10])
plt.imshow(p)
plt.colorbar();

# Valeurs et vecteurs propres d'une matrice

In [ ]:
from IPython.display import HTML
HTML('<iframe width="560" height="315" src="https://www.youtube.com/embed/NV-xna7ftmk?rel=0&amp;controls=1&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>')

calculer les valeurs propres de la matrice $a$

$a =
\left(
\begin{array}{ccc}
-1 & 2 & 2\\
2 & 2 & -1\\
2 & -1 & 2\\
\end{array}
\right)$

In [ ]:
a = np.array([[-1,2,2],[2,2,-1],[2,-1,2]])
a

In [ ]:
l,v = np.linalg.eig(a)

In [ ]:
l

In [ ]:
v